### ISSUE TITLE
Not downloading all img tags consistently, and not parsing last URL in a list

### ISSUE THREAD

**Issue by smokeblower** [sixcious/downloadyze#2]
Hi!  Thank you for coding this.  My task is to grab all the .jpeg images in a list of over 800 URLs from the same website.  There is a .jpeg file in each page, and only one, but so far downloadyze is grabbing some but not all.  Here's the URL from one it did grab:
https://ctbids.com/estate-sale/12157/item/1089361
and here's a URL where it didn't, though it did grab the other img files:
https://ctbids.com/estate-sale/12157/item/1089362

Thoughts?  I have download options time set at 3 seconds

In truth I only need the .jpeg files, nothing else, but since .jpeg is not an option in file type, I chose all img tags instead.

Also the last URL in a list of 10 did not get parsed.  I included a CR after each entry including the last one, so not sure what happened.

I'm doing these in batches of 10, but may make the lists longer once I'm more confident in what it does.

Thank you very much!

Greg, AKA SmokeBlower
I'm in southern California, so PST time zone.

**Comment by sixcious** [comment]
Hi Greg,

Thanks for opening this issue!

Just so I can try and reproduce this, could you please let me know what browser, browser version, and Downloadyze version you're using? Also, could you share a couple screenshots of the settings you're using? Specifically, I just need to see both the Download and Auto settings. Also which Multi Action are you using? URL List?

When I visit both those example URLs you provided, under the File Extensions strategy, `jpeg` shows up for me (there's around 9-11 jpeg files on both those pages), yet you have to use the Tags strategy and choose the `img` tag, and you're only getting one jpeg per page? So something seems different.

This is what I'm seeing when visiting https://ctbids.com/estate-sale/12157/item/1089362:
![Downloadyze-Issue-2](https://user-images.githubusercontent.com/1027814/206753883-a624f89c-31e4-47eb-a480-8e30458e2732.PNG)

As for the URL List action not visiting the last URL, yes, I can confirm that this is an error. That will be fixed in the next version update. Thanks for reporting this!

**Comment by sixcious** [comment]
Thanks for the extra information and screenshots!

So, after looking into this website more, it seems like it's loading its images in a delayed fashion using AJAX. My best guess is that sometimes the images haven't yet appeared by the time Downloadyze scans the page. You have the right Auto setting checked, `Wait for page to load`, but even after the `load` event has fired, the page uses AJAX to bring in the images. My guess is that sometimes it might take longer than 5 seconds. My way to combat this is to increase the Auto `Seconds` to a safer number. Have you tried increasing it to at least 10 seconds to see if it helps?

I tested downloading 10 pages at 5 seconds and noticed it did miss one page's images for me, but when I put it at 10 seconds, it downloaded all the pages.

Also, if this helps, to just download the jpeg img tags, and not the others, you could type in `jpeg` in the `URL Includes` filter, and it should only download the jpeg file.

Let me know if things change with the increased Auto seconds.
Thanks again!

**Comment by smokeblower** [comment]
Thank you so much!  Away from the desktop for the rest of the day.  Makes
sense about delayed loading. Will try all this tomorrow and report back.

Greg

**Comment by smokeblower** [comment]
Everything you suggested seems to have worked.  I have horribly poor internet service where I am, relying on a T-Mobile hotspot.  So sometimes timeouts are unavoidable.  Thank you again for your guidance.

**Comment by sixcious** [comment]
Awesome, thanks for letting me know! I'll try to get that other bug with the URL List fixed for the next update. Thanks again.

**Comment by sixcious** [comment]
Hi, I'm sorry for the super long delay.

The bug with it not downloading the last List URL should now be fixed in Version 3, which was released last week.

Thank you again! ❤️
