### ISSUE TITLE
How to simply download the full .html of the web page?

### ISSUE THREAD

**Issue by devinschumacher** [sixcious/downloadyze#3]
i just want to navigate through URL list and download the full .html page. 

but when i setup my settings in such a way it downloads all the individual files like every .js, .png, etc.

**Comment by sixcious** [comment]
Hi, thanks for opening this issue!

In the UI Window, for the `Download Strategy` dropdown, select the last option `Download the web page` and it will download just the html of the page.  Then select the URL List Multi Page Action and enter the list of URLs and toggle on AUTO at the bottom left if you want it to automatically go to each URL and download for you.

Let me know if that helps answer your question.

**Comment by devinschumacher** [comment]
awesome that worked. 
is there a way to randomize the settings? like wait times and movements and stuff to make it harder to be flagged as automation?

**Comment by sixcious** [comment]
Hi again!

No, I didn't think to add that. I think websites mainly seem to flag you if you're downloading too many things too quickly rather than evenly spaced apart. I would try to keep increasing either the Download `Delay` (for individual files) or Auto `Seconds` (for each page) and see if there's a minimum delay the website likes. If more sites start doing this type of automation check, I can try to add it in the future though.

Maybe a `Max Concurrent Downloads` setting may be useful, so it's only downloading one or two files at a time. This starts creeping into adding a download manager to give you a view of all the pending/scheduled downloads. It's something I wish I could add, but realistically it probably won't happen for a long time.

Sorry. 😞

**Comment by devinschumacher** [comment]
thats okay i appreciate the reply either way. i had an idea for a chrome extension kinda like that, except that instead of automating the page visits, it would just download every page you manually visit. 

that way you could give it to a click-farm type place overseas and have 20 people clicking around a website for a while and get a bunch of downloads but the browser wouldnt sense any automation
