### ISSUE TITLE
      Having Trouble With Downloading Multiple JPEG From Website 

### ISSUE THREAD

**Issue by CraigAndrewJohnson** [sixcious/downloadyze#4]
Hi, I am having issues with something i am trying to do i am new to using this extension and even to the whole scrapping webpages but what i am trying to do is download multiple JPEG Files Mostly 1-3 JPEG files per Page and i am having difficulty Performing this  automatically as i don't know how to set this up properly i will attach images to what i mean there are 1215 pages on the website but i am not sure how to set it up so they are also scanned for JPEG images and downloaded automatically thank you for all the help in advance (I Covered some of the content to protect the data and for security purposes in the images provided)
![Screenshot 2024-01-22 at 6 59 57 am](https://github.com/sixcious/downloadyze/assets/157314380/310a036c-0a48-4d6b-8114-424deef68cf6)
![Screenshot 2024-01-22 at 7 00 30 am](https://github.com/sixcious/downloadyze/assets/157314380/382dbf7b-910d-4f95-9fa9-8feb6a34841a)

**Comment by sixcious** [comment]
Hi! I'm sorry for the delay, I totally missed this.

If you still need help, here are some tips. First, you'll want to navigate to the very first page that has the jpg images you want. You'll also definitely want to use Downloadyze in `Multi Page` Mode. Then you have to configure three things: the Action, Download, and AUTO settings:

- For the Action, you'll need to see how the website is navigating you to the next page. Websites aren't consistent in this regard. Because you can't share the website due to security reasons (which is totally fine) you'll need to see how the website is doing this by clicking the next page button and observing if it's navigating you to another URL. You can also use your browser's "DevTools" function (Right Click > Inspect). Most websites will use an `a` or anchor tag, so you'd use the `Next Link` action. In that case, you'll need to inspect the page and give it a Selector or XPath for the `Next Rule`. If you see something like `page=2` in the URL, then the easiest action to use would be `Increment URL`, which allows you to select the number in the URL and no rule is needed.
- For the Download settings, for the `Download Strategy`, you could select `Download by file extension` and if you see `jpg` or `jpeg` show up, you can check those checkboxes. If you don't see them, then you could try `Download by tags` and see if any `img` tags show up.
- Toggle on `AUTO` in the bottom-left corner and you can set the number of `Times` (the total number of pages you want, e.g. 1215) and the `Seconds` would be how long it should wait on each page. If the website is complex and takes some time to load, I would recommend a minimum of 10 seconds, but you can go as low as 5.

The hardest one is going to be the Action settings, because that's the one that is website-specific and most website aren't consistent on.

I hope this helps a little! 💜
